//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_DBFirst_23032022
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        public int id { get; set; }
        public string isim { get; set; }
        public string soyisim { get; set; }
        public string email { get; set; }
        public string cinsiyet { get; set; }
        public System.DateTime dogumtarihi { get; set; }
        public Nullable<bool> durum { get; set; }
    }
}
