//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_DBFirst_23032022
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunRaporu
    {
        public string UrunAdi { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public Nullable<short> Stok { get; set; }
        public string KategoriAdi { get; set; }
        public string SirketAdi { get; set; }
    }
}
